version: 0.2
env:
  variables:
    BRANCH: "master"

phases:
  pre_build:
    commands:
      - echo "Branch is $BRANCH"
  build:
    commands:
      - echo Build completed on `date`
  post_build:
    commands:
      - echo PostBuild completed on `date`
