version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ./bye
  build:
    commands:
      - echo Build completed on `date`
  post_build:
    commands:
      - echo PostBuild completed on `date`
